### ISSUE TITLE
Aave interest calculation can be manipulated

### ISSUE THREAD

**Issue by mgcolburn** [dforce-network/dToken#13]
Severity: Informational

### Description
Aave interest is defined as the difference between the current balance (the result of a call to `balanceOf`) and the principal balance (the result of a call to `principalBalanceOf`). The difference is that `balanceOf` will return theoretical, but not-yet-minted ATokens.

```
    function _updateInterest(address _underlyingToken)
        internal
        returns (uint256)
    {
        uint256 _balance = getBalance(_underlyingToken);

        // Interest = Balance - UnderlyingBalance.
        uint256 _interest = _balance.sub(
            getUnderlyingBalance(_underlyingToken)
        );

        // Update the stored interest
        interestDetails[_underlyingToken] = interestDetails[_underlyingToken]
            .add(_interest);

        return _balance;
    }
```

However, theoretical tokens are minted (through calling `cumulateBalanceInternal`) upon any action such as a transfer or an interest stream redirection. As such, a user can trick the Aave handler into believing that no interest was generated.

The interest data isn't currently used on-chain, so it may not be a serious issue.

**Comment by Donald-Nobel** [comment]
OK, we have identified the issue, for example, here is the fix:
1. get aToken balanceof(handler) as A;
2. update interest as A - B; (for the very first time, B defaut to A); 
3. do mint / burn, etc;
4. get aToken balanceof(handler) as B;

A is the current principal and interest since the last time action; B is the principal for the last time action.
